{% set version = "0.0.3" %}

package:
  name: geolidar
  version: {{ version }}

source:
  # url: https://pypi.io/packages/source/g/geolidar/geolidar-{{ version }}.tar.gz
  # sha256: 2849305bc74e41718fd0eed8c1fc062e9efa47dfb5fa4a1dc1ef40c6bb9611a9
  git_url: https://github.com/tutorialcreation/GeoLidar.git
  # git_rev: 1.1.4
  # git_depth: 1 # (Defaults to -1/not shallow)


build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - python-pdal
    - geopandas
    - pandas
    - numpy
    - scipy
    - rasterio
    - gdal

test:
  imports:
    - imagesize

about:
  home: https://github.com/tutorialcreation/GeoLidar
  license: MIT
  summary: 'Loading and simple manipulations of lidar data'
  description: |
    This module loads makes loading of lidar data smooth
  dev_url: https://github.com/tutorialcreation/GeoLidar
  doc_url: https://pypi.org/project/geolidar/
  doc_source_url: https://github.com/tutorialcreation/GeoLidar/blob/main/README.md