# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: geolidar

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]


jobs:
  example-1:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.10"]
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Conda info
        shell: bash -l {0}
        run: |
        if [ -f requirements.txt ]; then conda create -y --name py37 python=3.7 &&
        conda install --force-reinstall -y -q --name py37 -c conda-forge --file requirements.txt &&
        conda activate py37; fi
      - name: Conda list
        shell: pwsh
        run: conda list
      - name: Test with pytest
        run: |
        python -m unittest discover tests/


